version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: subscription_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscriptions"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    container_name: subscription_service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: /app/config/local.yaml
    volumes:
      - ./config:/app/config
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
