server:
  port: 8080

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: subscriptions

logger:
  level: info         # debug, info, warn, error
  output: stdout      # stdout, stderr или путь к файлу